# Generated by Django 4.0.1 on 2022-02-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_tweet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='timestamp',
        ),
    ]
