# Generated by Django 4.0.1 on 2022-07-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_tweet_id_alter_tweet_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user_id',
            new_name='user',
        ),
    ]
