# Generated by Django 4.0.1 on 2022-07-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_tweet_id_tweet_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='sid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
